### ISSUE TITLE
Unify perf pipeline between gnark and arkworks

### ISSUE THREAD

**Issue by asn-d6** [mmaker/zkalc#13]
In arkworks, we run all the tests (even ones not currently used by zkalc) and dump them on a file, and then `criterion.py` splits them into curves.

In gnark, we create one output file per curve, and then `golang.py` needs to be run individually for each file.

We should think of how we want our pipeline to be.

**Comment by mmaker** [comment]
To add more details to this issue. Once we run `make` inside backend, all data is stored in [perf/data](https://github.com/asn-d6/zkalc/tree/main/perf/data). There, files follows the structure `machine/library.json` or `machine/library-curve.json`

From there, we must produce the frontend jsons that are stored in [frontend/data](https://github.com/asn-d6/zkalc/tree/main/frontend/data). There, files follow the structure `curve/library/machine.json`.

Right now the conversion is done with a benchmark parser that lives in [perf/benchmark_parser](https://github.com/asn-d6/zkalc/tree/main/perf/benchmark_parser). As written in the [readme](https://github.com/asn-d6/zkalc/tree/main/perf), this process is done manually and is still prone to errors. We must make this step automatic.

To complicate things, this parser is fed with the full file `machine/library-curve.json` (that's the case for go files), or `machine/library` after filtering only curve results that are pertinent (with a good old grep, that's the case for criterion files). This lack of uniformity is not good either. 
We should be able to modify either our codebase to filter properly for curves, and [zkalc.sh](https://github.com/ConsenSys/gnark-crypto/blob/zkalc/zkalc.sh) should prepend more information about the curve we are working on.

**Comment by mmaker** [comment]
the pipeline is now there after the merge with zkharness' bench-data! :)
