### ISSUE TITLE
Social preview via opengraph tags

### ISSUE THREAD

**Issue by asn-d6** [mmaker/zkalc#36]
Kobi pointed out that the social preview of zkalc is very ugly -- that is, the image that appears when you paste zkalc links into twitter/telegram/etc.

Apparently some opengraph tags can fix that. Also, the <title> of zkalc is "Create Next App" right now. We can fix that too.

**Comment by mmaker** [comment]
I think this has been fixed right?

**Comment by asn-d6** [comment]
Yep. I think so.
