### ISSUE TITLE
Front-End / zchart axis labeling

### ISSUE THREAD

**Issue by b-wagn** [mmaker/zkalc#51]
The zchart presentation could be slightly improved by labeling the axis.
The y-axis is time of course, but for the x-axis a label explaining what it represents could help.

**Comment by mmaker** [comment]
that's a great point. If I'm not mistaken, according to [Nivo's documentation](https://nivo.rocks/line/) this can be solved with something like

```js
        axisBottom={{
            legend: 'size',
        }}
```

within [`ZkalcPlot`](https://github.com/mmaker/zkalc/blob/main/frontend/app/charts/page.js#L201). This seems a fairly easy change to make, do you want to give it a shot?
